version: '3.8'
services:
  vllm:
    image: vllm/vllm-openai:latest
    container_name: vllm_engine
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # volumes:
    #   - ~/.cache/huggingface:/root/.cache/huggingface
    # Using LLaVA for Vision support as discussed
    command: 
      --model RedHatAI/gemma-3-27b-it-FP8-dynamic
      --gpu-memory-utilization 0.9 
      --max-model-len 131072 
      --max-model-len 32768
      --tensor-parallel-size 2

  chatbot:
    build: .
    container_name: streamlit_app
    network_mode: host
    depends_on:
      - vllm
    volumes:
      - .:/app
      - ./app_data.db:/app/app_data.db
      - ./chroma_db:/app/chroma_db
      - ./extracted_images:/app/extracted_images
    environment:
      - VLLM_URL=http://localhost:8000/v1